prometheus:
  prometheusSpec:
    retention: 3d
    scrapeInterval: 30s
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  replicas: 1
  adminPassword: admin123
  resources:
    requests:
      cpu: 100m
      memory: 256MiMi
    limits:
      cpu: 1000m
      memory: 512Mi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi

nodeExporter:
  enabled: true
