apiVersion: argoproj.io/v1alpha1
kind: Apllication

metadata:
  name: phoneix-app
  namespace: argocd

spec:
  project: default
  
  source:
    repoURL: https://github.com/Abhishek0609om/EKS-GitOps-Engine-.git
    targetRevision: main
    path: k8s-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true