name: Phoenix Production CI Pipeline
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-secure:
    name: Build, Scan, and ship Container
    runs-on: ubuntu-latest
    steps:
    # clone the repo into the runner machine
      - name: checkout code 
        uses: actions/checkout@v4

    # Initialize your aws credentials securely 
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

    # log into your amazon ecr registry
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

    # run the Trivy security scanner on your raw code workspace 
      - name: Run TRIVY Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table' 
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # Build the docker image and push to ECR
      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: phoenix-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      # Corrected manifest Update and Cross-Repo Push step
      - name: syn and push manifest Repo 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: phoenix-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          #clone and dedicated manifest repository 
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Abhishek0609om/phoenix-manifests-.git

          #update the image tag directly inside the local copy of your k8s-manifests directory 
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|I" k8s-manifests/deployment.yaml

          #copy of updated infrastructure configurations over to you cloned repo folder 
          cp k8s-manifests/* phoenix-manifests-/

          #change directory INTO the repository to run Git management commands
          cd phoenix-manifests-

          #Configure Git identity credentials inside the active directory
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          #push 
          git add .
          git commit --allow-empty -m "chore: update application container image version to $IMAGE_TAG [skip ci]"
          git push origin main 